name: Create, Test, and Publish Docker Image

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - scripts/create-predevals-data.R
      - Dockerfile
      - renv.lock
      - renv/
      - .Rprofile
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      publish:
        required: true
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PUBLISH: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && inputs.publish) }}

jobs:
  build-image:
    permissions: read-all
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      test-tag: ${{ steps.name-artifact.outputs.tag }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0 
      - id: container-login
        if: ${{ env.PUBLISH }}
        name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 #v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=ref,event=branch
      - id: name-artifact
        env:
          REPO: ${{ github.repository }}
          TAG: ${{ steps.meta.outputs.tags }}
          LABEL: ${{ steps.meta.outputs.labels }}
        run: |
          echo $TAG
          echo $LABEL
          # This allows us to parse the case when there are multiple tags. 
          tag=$(echo $TAG | sed -e "s+[^:]*[:]\([^ ]*\).*+\1+")
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "name=tag-$tag" >> "$GITHUB_OUTPUT"
        shell: bash {0}
      - id: build
        name: Build and export
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 #v6.16.0
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/hubpredevalsdata-docker.tar
      - id: test
        name: Test image
        env:
          TAG: ${{ steps.name-artifact.outputs.tag }}
        run: |
          # Testing strategy here: test the same data built with the two 
          # versions of the image. There is a script called test.R that will
          # compare them. 
          # SETUP -------------------------------------------------------------
          echo "::group::Setup: cloning test repo and pulling images"
          mkdir -p testing && cd testing
          git clone https://github.com/reichlab/flu-metrocast.git
          curl -sSL -o predevals-config.yml https://raw.githubusercontent.com/reichlab/metrocast-dashboard/refs/heads/main/predevals-config.yml
          mkdir -p latest
          mkdir -p new
          docker pull ghcr.io/hubverse-org/hubpredevalsdata-docker:latest
          docker load --input /tmp/hubpredevalsdata-docker.tar
          echo "::endgroup::"
          echo "::group::[latest] Generating data with the latest image"
          # GENERATE LATEST ---------------------------------------------------
          docker run --rm -i -v "$(pwd)":"/project" \
            "ghcr.io/hubverse-org/hubpredevalsdata-docker:latest" \
            create-predevals-data.R \
            -h flu-metrocast \
            -d flu-metrocast/target-data/oracle-output.csv \
            -c predevals-config.yml \
            -o latest
          echo "::endgroup::"
          # GENERATE PR -------------------------------------------------------
          echo "::group::[${TAG}] Generating data with the ${TAG} image"
          docker run --rm -i -v "$(pwd)":"/project" \
            "ghcr.io/hubverse-org/hubpredevalsdata-docker:${TAG}" \
            create-predevals-data.R \
            -h flu-metrocast \
            -d flu-metrocast/target-data/oracle-output.csv \
            -c predevals-config.yml \
            -o new
          echo "::endgroup::"
          # COMPARE OUTPUTS ---------------------------------------------------
          echo "::group::[validation] comparing output data sets"
          docker run --rm -i -v "$(pwd)":"/project" \
            "ghcr.io/hubverse-org/hubpredevalsdata-docker:${TAG}" \
            test.R latest new
          echo "::endgroup::"
      - id: upload
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: ${{ steps.name-artifact.outputs.name }}
          path: /tmp/hubpredevalsdata-docker.tar

  test:
    needs: [build-image]
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main') }}
    name: "Test built image against published test suite (may fail)"
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - id: check-artifacts
        name: Fetch image
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: tag*
      - id: test-image
        name: Test image against tests on main
        env:
          TAG: ${{ needs.build-image.outputs.test-tag }}
        run: |
          path=$(ls artifacts/*/*)
          # Testing strategy here: test the same data built with the two 
          # versions of the image. There is a script called test.R that will
          # compare them. 
          echo "::group::Setup: cloning test repo and pulling images"
          git clone https://github.com/reichlab/flu-metrocast.git
          curl -sSL -o predevals-config.yml https://raw.githubusercontent.com/reichlab/metrocast-dashboard/refs/heads/main/predevals-config.yml
          mkdir -p latest
          mkdir -p new
          docker pull ghcr.io/hubverse-org/hubpredevalsdata-docker:latest
          docker load --input "$path"
          echo "::endgroup::"
          echo "::group::[latest] Generating data with the latest image"
          # GENERATE LATEST ---------------------------------------------------
          docker run --rm -i -v "$(pwd)":"/project" \
            "ghcr.io/hubverse-org/hubpredevalsdata-docker:latest" \
            create-predevals-data.R \
            -h flu-metrocast \
            -d flu-metrocast/target-data/oracle-output.csv \
            -c predevals-config.yml \
            -o latest
          echo "::endgroup::"
          # GENERATE PR -------------------------------------------------------
          echo "::group::[${TAG}] Generating data with the ${TAG} image"
          docker run --rm -i -v "$(pwd)":"/project" \
            "ghcr.io/hubverse-org/hubpredevalsdata-docker:${TAG}" \
            create-predevals-data.R \
            -h flu-metrocast \
            -d flu-metrocast/target-data/oracle-output.csv \
            -c predevals-config.yml \
            -o new
          echo "::endgroup::"
          # COMPARE OUTPUTS ---------------------------------------------------
          echo "::group::[validation] comparing output data sets"
          docker run --rm -i -v "$(pwd)":"/project" \
            "ghcr.io/hubverse-org/hubpredevalsdata-docker:${TAG}" \
            test.R latest new
          echo "::endgroup::"
        shell: bash
  publish:
    needs: [build-image]
    name: "Publish Image"
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && inputs.publish) }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - id: check-artifacts
        name: Fetch Image
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: tag*
      - id: container-login
        name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: load-image
        run: |
          path=$(ls artifacts/*/*)
          docker load --input "$path"
        shell: bash
      - id: push
        name: Build and Publish
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 #v6.16.0
        with:
          tags: ${{ needs.build-image.outputs.tags }}
          push: ${{ fromJSON(env.PUBLISH) }}
          labels: ${{ needs.build-image.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: ${{ fromJSON(env.PUBLISH) }}


